### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by pcgeek86**
Included details for discovering the acceptable values for the TimeZone property of the xTimeZone DSC Resource.

### CODE REVIEW

**Comment by joeyaiello** [comment]
I'd actually recommend using this instead: 

```powershell
[System.TimeZoneInfo]::GetSystemTimeZones().Id
```

It's more clear what's going on, no regex black magic, and it doesn't use a blackbox exe.

**Comment by pcgeek86** [comment]
Good idea. Microsoft developed the DSC Resource, so I'm just keeping consistency with how it was written. Not sure if there are differences between the .NET Base Class Library (BCL) vs. the tzutil.exe, so consistency is key.

However, looking at the output from your command, it does appear that it has consistent output with  `tzutil.exe /l`.

Might want to recommend to the DSC Resource author to update their code to avoid using "black box exe's."

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
@joeyaiello Updated per your request.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by TravisEz13** [comment]
Per [contribution guidelines], (https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-reqeust), please resubmit to dev.

**Comment by TravisEz13** [comment]
This was submitted to dev, thanks again

**Pull request closed without merging**
