### PR TITLE
Added support for Set-Timezone to use .NET reflection if possible - Fixes #5

### LINKED ISSUE #5: xTimeZone module should use .NET APIs instead of tzutil.exe
The xTimeZone module should use .NET APIs instead of the tzutil.exe program to perform automation tasks. Wrapping exe's is obviously an option, but should be used as a last resort, as it's less PowerShell-friendly, compared to using native APIs and cmdlets.

Thanks to @joeyaiello for this idea.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

### PR DESCRIPTION
**Pull request by PlagueHO**
Changes:
```
* xTimeZone: Moved Get-Timezone and Set-Timezone to TimezoneHelper.psm1
             Added unit tests for TimezoneHelper.psm1
             Converted Get-Timezone to use CIM cmdlets.
             Added support for Set-Timezone to use .NET reflection if possible.
             Added message localization support.
* Copied SetTimeZone.ps1 example into Readme.md.
```

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xtimezone/17)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/TimezoneHelper.psm1, line 70 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb24SlE1VkLpDMnPEH:-KFb24SlE1VkLpDMnPEI:-1394342216) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L70)):*
Is running when the type is already loaded supported in WMF 4 and WMF5?  can we add an explicit test for this?
if running on 5, you can start a job in 4 using: start-job -PSVersion 4.0 -ScriptBlock {<script>} | Receive-Job -Wait
ping me if you need help

---

*[DSCResources/TimezoneHelper.psm1, line 71 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb-s4kEi9qm2dAkfrg:-KFb-s4kEi9qm2dAkfrh:-1560632520) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L71)):*
suggestion, but the cs code in a  .cs file and read it using get-content -raw and pass it to add-type... it'll make the code look better.

---

*[DSCResources/TimezoneHelper.psm1, line 324 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb09tqD0Ra6DUhpwNJ:-KFb09tqD0Ra6DUhpwNK:1234212008) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L324)):*
Need to replace the Console.WriteLine they will cause an error in WMF 4

---

*[DSCResources/xTimeZone/xTimeZone.psm1, line 122 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb1dr6Zthpl2Q1xHQB:-KFb1dr75Ys-IY4jUQde:-627647666) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/xTimeZone/xTimeZone.psm1#L122)):*
can you clarify this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/17)*

**Comment by PlagueHO** [comment]
Review status: 3 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/TimezoneHelper.psm1, line 70 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb24SlE1VkLpDMnPEH:-KFbFZc2RJIz6tPGURw4:1807762354) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L70)):*
I've added a test to detect if the type is already defined so that for both WMF4 or WMF5 if it is already defined then it won't be redefined.

---

*[DSCResources/TimezoneHelper.psm1, line 71 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb-s4kEi9qm2dAkfrg:-KFbFr7di4f-vubDhEt6:-1445576500) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L71)):*
Excellent idea. Have implemented.

---

*[DSCResources/TimezoneHelper.psm1, line 324 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb09tqD0Ra6DUhpwNJ:-KFbTeFrI5o-_7lLw2ZN:441299029) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L324)):*
I can't seem to replicate this problem. Do you know what it should be replaced with?

---

*[DSCResources/xTimeZone/xTimeZone.psm1, line 122 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb1dr6Zthpl2Q1xHQB:-KFbH-re7a2kvSf6n2WQ:-1144502767) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/xTimeZone/xTimeZone.psm1#L122)):*
I have removed it - not necessary on such a small if...else block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/17)*

**Comment by TravisEz13** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/SetTimeZone.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbkB_Gvda8JAnB50mj:-KFbkB_Gvda8JAnB50mk:1722555549) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L7)):*
Probably should change the namespace.  Microsoft.PowerShell.xTimeZone or something similar

---

*[DSCResources/SetTimeZone.cs, line 252 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbiqrGvmuEsoufVqRT:-KFbiqrGvmuEsoufVqRU:-213052564) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L252)):*
Console.WriteLines need to be removed it will break wmf 4

---

*[DSCResources/SetTimeZone.cs, line 271 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbkVsxeTfNhKvEeEL0:-KFbkVsxeTfNhKvEeEL1:1343667756) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L271)):*
needs newline

---

*[DSCResources/TimezoneHelper.psm1, line 324 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb09tqD0Ra6DUhpwNJ:-KFbjiT5nlK-VWnOdA6W:-1976651763) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L324)):*
in these cases a throw access denied exception.  most of the error writes should be  throwing an appropriate exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/17)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/SetTimeZone.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbkB_Gvda8JAnB50mj:-KFc824E7FdWdkn79yVV:-499146009) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L7)):*
Done.

---

*[DSCResources/SetTimeZone.cs, line 252 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbiqrGvmuEsoufVqRT:-KFcJfTNpOzG0WCD8pF4:-499146009) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L252)):*
Done.

---

*[DSCResources/SetTimeZone.cs, line 271 \[r2\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFbkVsxeTfNhKvEeEL0:-KFc86-SXAs6Fyb-Venv:-499146009) ([raw file](https://github.com/powershell/xtimezone/blob/9c47f0e083d6c67f0bf1b9c4e033acdd1b63f1d5/DSCResources/SetTimeZone.cs#L271)):*
Done.

---

*[DSCResources/TimezoneHelper.psm1, line 324 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFb09tqD0Ra6DUhpwNJ:-KFc8Espy3bCvsMJnaTM:254024363) ([raw file](https://github.com/powershell/xtimezone/blob/58ec90c48d748e59c21e6fdefa1da1e5061a4fa9/DSCResources/TimezoneHelper.psm1#L324)):*
Ah right. Silly me. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/17)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/SetTimeZone.cs, line 259 \[r3\]](https://reviewable.io:443/reviews/powershell/xtimezone/17#-KFf6tMj0lP6excVEYuM:-KFf6tMj0lP6excVEYuN:842798422) ([raw file](https://github.com/powershell/xtimezone/blob/f936e0c895f17da53495bf888dd39a419667f5f0/DSCResources/SetTimeZone.cs#L259)):*
System exception is probably not specific enough, but this is not blocking

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/17)*

**Comment by TravisEz13** [comment]
Thanks for your contribution! :clap:

**Pull request merged**
