### PR TITLE
Add Deprecated Message - Fixes #33

### LINKED ISSUE #33: Combine TimeZoneDsc Resource with ComputerManagementDsc
As we are going to be changing this resource over to TimeZoneDsc in the near future it might make sense to move it over to make it part of ComputerManagementDsc during the move. I would also suggest doing the same with SystemLocaleDsc.

@kwirkykat - do you have any thoughts on this? I'm happy to keep them separate but I thought it might simplify things as these "individual" resources make more sense together.

And if we're implementing the fairly destructive changes of renaming the modules to *Dsc, this would seem to be the best time to do it.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR adds a deprecated message to the README.MD. It should be merged once https://github.com/PowerShell/ComputerManagementDsc/pull/158 has been merged.

**This Pull Request (PR) fixes the following issues:**
- Fixes #33

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Could you please review @johlju ?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xtimezone/36)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

Reminder to either of us: Change the repository description as well once this is merged. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xtimezone/36#-:-LCDnL2Y06BAR4jUD2mq:bplpq60)*

**Comment by johlju** [comment]
@PlagueHO I updated the repo description as well.

**Comment by PlagueHO** [comment]
@johlju - Awesome! We should also release this to Master as well. Do we do this as part of the normal monthly release or do it as a one off PR.

**Comment by johlju** [comment]
@PlagueHO Hmm... let me run that by Katie. Could you send in PR to update Maintainers.md in DscResources too?

**Comment by johlju** [comment]
@PlagueHO On second thought, I think we wait until next release since we probably can get more resource moved in the mean time. If this should be a problem then we can discuss it again. 🙂

**Pull request merged**
