### PR TITLE
Fix Localization Problem with DSC Configuration TEST/GET

### PR DESCRIPTION
**Pull request by guitarrapc**
See detail at https://github.com/PowerShell/xTimeZone/issues/20

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xtimezone/21)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/TimezoneHelper.psm1, line 76 \[r1\]](https://reviewable.io:443/reviews/powershell/xtimezone/21#-KKoOxgi8WLbgR8Ez6gN:-KKoOxgi8WLbgR8Ez6gO:-230145694) ([raw file](https://github.com/powershell/xtimezone/blob/060dd9346c8811b717c5a93742b5bb28c0313b09/DSCResources/TimezoneHelper.psm1#L76)):*
> ```PowerShell
>     # Test Expected is same as Current
>     $currentId = Get-TimeZoneId -TimeZone (Get-TimeZone)
> ```

Please add unit tests for the new functions.

It is required that you provide adequate test coverage for the code you change. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/21)*

**Comment by TravisEz13** [comment]
Please fix test breaks

**Comment by PlagueHO** [comment]
@guitarrapc  - I'll submit a PR to your repo with the updated unit tests.

**Comment by PlagueHO** [comment]
@guitarrapc, @TravisEz13 - I've added/updated the unit tests for this PR. All passing now. You can review if you like @TravisEz13. Thanks!

**Comment by guitarrapc** [comment]
@PlagueHO Thank you so much. LGTM.

**Comment by PlagueHO** [comment]
@guitarrapc - no problem! A pleasure to help!

**Comment by TravisEz13** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xtimezone/21)*

**Pull request merged**
